services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    depends_on:
      - composer
    networks:
      - laravel-network

  composer:
    image: composer:2.6
    volumes:
      - .:/app
    working_dir: /app
    command: composer install
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
